version: '2'
services:
  vault-1:
    hostname: vault-1
    image: &vault-version vault:1.8.2
    ports:
      - "8210:8200"
    restart: always
    volumes:
      - vault-1:/vault/file
      - ./volumes/config:/vault/config
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault1.json
  vault-2:
    depends_on:
      - vault-1
    hostname: vault-2
    image: *vault-version
    ports:
      - "8220:8200"
    restart: always
    volumes:
      - vault-2:/vault/file
      - ./volumes/config:/vault/config
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault2.json
  vault-3:
    depends_on:
      - vault-1
    hostname: vault-3
    image: *vault-version
    ports:
      - "8230:8200"
    restart: always
    volumes:
      - vault-3:/vault/file
      - ./volumes/config:/vault/config
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault3.json

volumes:
  vault-1:
  vault-2:
  vault-3:
